Repository Record-of-memory/Record-of-memory-Server, pull requests merged in 2023-02, with the labels that each got.

#13 [FIX]: 좋아요 취소 메서드 변경
  src/main/java/com/rom/domain/likes/presentation/LikesController.java
Labels: refactor 🪐

#15 [FEAT]: 스웨거 추가적인 설명을 위한 OpenApiConfig 추가
  src/main/java/com/rom/global/config/OpenApiConfig.java
Labels: feature 🎄

#16 [FEAT]: 유저 탈퇴 API 구현
  src/main/java/com/rom/domain/user/application/UserService.java
  src/main/java/com/rom/domain/user/domain/User.java
  src/main/java/com/rom/domain/user/presentation/UserController.java
Labels: feature 🎄

#19 [FIX]: 다이어리 API 수정
  src/main/java/com/rom/domain/diary/application/DiaryService.java
  src/main/java/com/rom/domain/diary/dto/LeaveDiaryReq.java
  src/main/java/com/rom/domain/diary/presentation/DiaryController.java
Labels: fix ☔️, refactor 🪐

#18 [FEAT]: 유저 프로필 업데이트 API 구현
  src/main/java/com/rom/domain/record/application/RecordService.java
  src/main/java/com/rom/domain/user/application/UserService.java
  src/main/java/com/rom/domain/user/dto/UpdateProfileReq.java
  src/main/java/com/rom/domain/user/presentation/UserController.java
  src/main/java/com/rom/global/infrastructure/S3Uploader.java
Labels: feature 🎄, refactor 🪐

#20 [FIX]: 유저 탈퇴할 때 Refresh 토큰도 같이 삭제 하도록 수정
  src/main/java/com/rom/domain/user/application/UserService.java
  src/main/java/com/rom/domain/user/presentation/UserController.java
Labels: fix ☔️, feature 🎄

#21 [FEAT]: 다이어리 정보 조회 API 구현(유저목록, 일기목록 동시 조회 가능)
  src/main/java/com/rom/domain/diary/application/DiaryService.java
  src/main/java/com/rom/domain/diary/domain/Diary.java
  src/main/java/com/rom/domain/diary/dto/DiaryDetailRes.java
  src/main/java/com/rom/domain/diary/dto/DiaryListRes.java
  src/main/java/com/rom/domain/diary/dto/DiaryRecordDetailRes.java
  src/main/java/com/rom/domain/diary/presentation/DiaryController.java
Labels: fix ☔️, feature 🎄

#17 [FEAT] 일기 조회 세분화 및 이미지 추가
  src/main/java/com/rom/domain/record/application/RecordService.java
  src/main/java/com/rom/domain/record/domain/repository/RecordRepository.java
  src/main/java/com/rom/domain/record/dto/RecordDateReq.java
  src/main/java/com/rom/domain/record/dto/RecordDetailReq.java
  src/main/java/com/rom/domain/record/dto/RecordDetailRes.java
  src/main/java/com/rom/domain/record/dto/RecordsByUserReq.java
  src/main/java/com/rom/domain/record/presentation/RecordController.java
Labels: fix ☔️, feature 🎄

#24 [FIX]: 좋아요 취소 API 수정
  src/main/java/com/rom/domain/comment/domain/Comment.java
  src/main/java/com/rom/domain/likes/application/LikesService.java
  src/main/java/com/rom/domain/likes/dto/CancelLikeReq.java
  src/main/java/com/rom/domain/likes/presentation/LikesController.java
Labels: fix ☔️

#25 [CHORE]: 좋아요 취소 컨트롤러 변수 수정
  src/main/java/com/rom/domain/comment/presentation/CommentController.java
  src/main/java/com/rom/domain/likes/application/LikesService.java
  src/main/java/com/rom/domain/likes/presentation/LikesController.java
Labels: chore 💪

#27 [FEAT]: 검색어에 해당하는 제목의 일기 조회 API 구현
  src/main/java/com/rom/domain/diary/application/DiaryService.java
  src/main/java/com/rom/domain/diary/presentation/DiaryController.java
Labels: feature 🎄

#26 [FEAT]: Email로 유저 정보 조회 API 구현
  src/main/java/com/rom/domain/user/application/UserService.java
  src/main/java/com/rom/domain/user/presentation/UserController.java
Labels: feature 🎄

#29 [FIX]: 다이어리 목록 조회 API 응답 수정, 다이어리 타입 변경 로직 추가
  src/main/java/com/rom/domain/diary/application/DiaryService.java
  src/main/java/com/rom/domain/diary/domain/Diary.java
  src/main/java/com/rom/domain/diary/dto/DiaryListRes.java
Labels: fix ☔️, feature 🎄

#31 [FIX]: 타임존 asia/seoul로 설정
  src/main/java/com/rom/ROMApplication.java
Labels: fix ☔️

#35 [FEAT]: 좋아요 클릭여부 API 구현
  src/main/java/com/rom/domain/likes/application/LikesService.java
  src/main/java/com/rom/domain/likes/domain/repository/LikesRepository.java
  src/main/java/com/rom/domain/likes/dto/LikeClickedRes.java
  src/main/java/com/rom/domain/likes/presentation/LikesController.java
Labels: fix ☔️, feature 🎄

#38 [FIX]: 일기 수정 시 이미지도 수정 가능하게 변경
  src/main/java/com/rom/domain/record/application/RecordService.java
  src/main/java/com/rom/domain/record/domain/Record.java
  src/main/java/com/rom/domain/record/presentation/RecordController.java
Labels: fix ☔️, feature 🎄

#44 [FEAT]: 그리드뷰 일기 조회 API 개발
  src/main/java/com/rom/domain/record/application/RecordService.java
  src/main/java/com/rom/domain/record/domain/Record.java
  src/main/java/com/rom/domain/record/domain/repository/RecordRepository.java
  src/main/java/com/rom/domain/record/dto/GridRecordRes.java
  src/main/java/com/rom/domain/record/dto/GridResultDetailRes.java
  src/main/java/com/rom/domain/record/dto/GridResultRes.java
  src/main/java/com/rom/domain/record/dto/GridUserRes.java
  src/main/java/com/rom/domain/record/dto/WriteRecordReq.java
  src/main/java/com/rom/domain/record/presentation/RecordController.java
Labels: feature 🎄

#45 [FIX] Swagger 수정 및 Get 메소드 Parameter로 변경
  src/main/java/com/rom/domain/record/application/RecordService.java
  src/main/java/com/rom/domain/record/dto/RecordDateReq.java
  src/main/java/com/rom/domain/record/dto/UpdateRecordReq.java
  src/main/java/com/rom/domain/record/dto/WriteRecordNoImgReq.java
  src/main/java/com/rom/domain/record/dto/WriteRecordReq.java
  src/main/java/com/rom/domain/record/presentation/RecordController.java
Labels: fix ☔️

#46 [FIX]: 다이어리 조회 시 이미지가 보이지 않는 문제 해결
  src/main/java/com/rom/domain/diary/application/DiaryService.java
  src/main/java/com/rom/domain/record/application/RecordService.java
  src/main/java/com/rom/domain/record/dto/WriteRecordReq.java
  src/main/java/com/rom/domain/record/presentation/RecordController.java
Labels: fix ☔️

#56 [FEAT]: 다이어리 이름 수정 API 개발
  src/main/java/com/rom/domain/diary/application/DiaryService.java
  src/main/java/com/rom/domain/diary/dto/UpdateDiaryReq.java
  src/main/java/com/rom/domain/diary/presentation/DiaryController.java
  src/main/java/com/rom/domain/record/application/RecordService.java
Labels: feature 🎄

#57 [FEAT]: 이메일로 임시 비밀번호 발급 기능 추가
  .gitignore
  build.gradle
  src/main/java/com/rom/domain/user/application/UserService.java
  src/main/java/com/rom/domain/user/domain/repository/UserRepository.java
  src/main/java/com/rom/domain/user/dto/SendPasswordReq.java
  src/main/java/com/rom/domain/user/presentation/UserController.java
  src/main/resources/application.yml
Labels: documentation 🥟, feature 🎄

#58 [FEAT]: 다이어리 수정, 임시 비밀번호 발급
  .gitignore
  build.gradle
  src/main/java/com/rom/domain/diary/application/DiaryService.java
  src/main/java/com/rom/domain/diary/dto/UpdateDiaryReq.java
  src/main/java/com/rom/domain/diary/presentation/DiaryController.java
  src/main/java/com/rom/domain/record/application/RecordService.java
  src/main/java/com/rom/domain/user/application/UserService.java
  src/main/java/com/rom/domain/user/domain/repository/UserRepository.java
  src/main/java/com/rom/domain/user/dto/SendPasswordReq.java
  src/main/java/com/rom/domain/user/presentation/UserController.java
  src/main/resources/application.yml
Labels: feature 🎄

#59 [FIX]: 임시 비밀번호 발급, 댓글 조회 API 수정
  src/main/java/com/rom/domain/auth/application/AuthService.java
  src/main/java/com/rom/domain/auth/dto/SendPasswordReq.java
  src/main/java/com/rom/domain/auth/presentation/AuthController.java
  src/main/java/com/rom/domain/comment/application/CommentService.java
  src/main/java/com/rom/domain/user/application/UserService.java
  src/main/java/com/rom/domain/user/domain/repository/UserRepository.java
  src/main/java/com/rom/domain/user/presentation/UserController.java
Labels: fix ☔️

#60 [FIX]: 임시 비밀번호 발급, 댓글 조회 API 수정
  src/main/java/com/rom/domain/auth/application/AuthService.java
  src/main/java/com/rom/domain/auth/dto/SendPasswordReq.java
  src/main/java/com/rom/domain/auth/presentation/AuthController.java
  src/main/java/com/rom/domain/comment/application/CommentService.java
  src/main/java/com/rom/domain/user/application/UserService.java
  src/main/java/com/rom/domain/user/domain/repository/UserRepository.java
  src/main/java/com/rom/domain/user/presentation/UserController.java
Labels: fix ☔️

#62 [FIX]: CI 오류 수정
  src/main/java/com/rom/domain/user/application/UserService.java
  src/main/java/com/rom/domain/user/dto/SendPasswordReq.java
  src/main/java/com/rom/domain/user/presentation/UserController.java
Labels: fix ☔️

#63 [FIX]: 그리드뷰 수정, 댓글 조회 수정
  src/main/java/com/rom/domain/comment/application/CommentService.java
  src/main/java/com/rom/domain/comment/dto/FindCommentRes.java
  src/main/java/com/rom/domain/record/application/RecordService.java
Labels: fix ☔️

#65 [FIX]: 자신의 댓글만 삭제할 수 있도록 수정
  src/main/java/com/rom/domain/comment/application/CommentService.java
Labels: fix ☔️

#67 [FEAT]: 자신의 댓글 여부 판단 기능 추가
  src/main/java/com/rom/domain/comment/application/CommentService.java
  src/main/java/com/rom/domain/comment/dto/FindCommentRes.java
Labels: feature 🎄

#68 [FEAT]: 자신의 댓글 여부 판단 기능 추가
  src/main/java/com/rom/domain/comment/application/CommentService.java
  src/main/java/com/rom/domain/comment/dto/FindCommentRes.java
Labels: feature 🎄
